nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://doozescape.com', 'https://www.doozescape.com', 'https://doozescape.4escape.io']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600